### ISSUE TITLE
Unify installs

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#24]
Currently "python setup.py install" works differently from the recommended version. We should maybe migrate to a setup.cfg instead and use setuptools (called by a dummy setup.py) for the editable installs

**Comment by TheEimer** [comment]
Make sure that normal install works the same as editable install

**Comment by maximilianreimer** [comment]
I did a little bit of research on what is the recommended way to setup a python package. 

# Packaging and Build Dependencies
 from what I understand the current recommend way ist to have a `pyproject.toml` to declare build dependencies and use `setup.cfg` for the rest (Metadata and requirements) (see [Setuptools docs](https://setuptools.readthedocs.io/en/latest/build_meta.html))

According to the [setuptools quickstart guide](https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html#development-mode) In order to still enable editable installs one has to keep a `setup.py` only containing  
```
import setuptools
setuptools.setup()
```

# Other Config Files:
Another question where to configure the other tools we are using. I look up the docs and that are the recommend files:
| tools | `setup.cfg` | `pyproject.toml` | `tox.ini` | other  |
| :--- | :---- | :--- | :--- | :--- |
| pytest-cov | :heavy_check_mark: | (:heavy_check_mark:) | (:heavy_check_mark:) | 
| pytest |  (:heavy_check_mark:) | :heavy_check_mark: | :heavy_check_mark: | 
| black | :x: | :heavy_check_mark: | :x: |
| flake8 | :heavy_check_mark:  | :x: | :heavy_check_mark: | .flake8 |

- :heavy_check_mark: : recommended
- (:heavy_check_mark:): possible
- :x: : Not supported 

# Conclusion
Given this I would suggest having the following files: 
```
DACBench
├── setup.py: as above (for editable install)
├── setup.cfg: metadata, requirements and extras
├── pyproject.toml: build dependencies, pytest-cov, pytest, black
├── .flake8
```
I would prefer `.flake8` over `tox.ini` since its more transparent what it is fore. 
```
