### ISSUE TITLE
Update tests & runner

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#42]
Look through both, make sure all new benchmarks are covered and old ones are removed. Make runner more userfriendly.

**Comment by maximilianreimer** [comment]
While started implementing a couple of additional tests I stumble upon the following things: 

1.  In [`dacbench.abstract_benchmark.AbstractBenchmark.save_config`](https://github.com/automl/DACBench/blob/089e55a2e56045335896af21f3fcc0134b6268c2/dacbench/abstract_benchmark.py#L42) and [`dacbench.abstract_benchmark.AbstractBenchmark.read_config_file`](https://github.com/automl/DACBench/blob/089e55a2e56045335896af21f3fcc0134b6268c2/dacbench/abstract_benchmark.py#L192) are using field
    *  `observation_space`
    *  `action_space`
  but I couldn't find a single config file using those fields, are they still in use? 

2. The `read_config`methods has a way of handling the case where `observation_space_type": "None"` the saving methods not (requires at least `observation_space_args` to be in config). What is the expected behaviour?

**Comment by maximilianreimer** [comment]
In general, what is the threshold we want to achieve?

**Comment by maximilianreimer** [comment]
More information needed: 
1. What are old (to be removed) what are new ones? All benchmarks have at least 80% coverage
2. What are you missing for the runners? A cli?

**Comment by maximilianreimer** [comment]
* Remove `dacbench.runner.run_dacbench`
* Create new issue for imporvements for  `run_baselines`
   * DISCRETE_ACTIONS define based on action spaces of benchmark, (resultion maybe as parameter)
   * Opimal policies
   * ...

**Comment by TheEimer** [comment]
We want to remove benchmarks and update test respecitvely after merging branches (specifically cma)
