### ISSUE TITLE
Take Care of Warnings During Doc Build

### ISSUE THREAD

**Issue by maximilianreimer** [automl/DACBench#70]
There are currently a lot of warnings when building the docs.

**Comment by TheEimer** [comment]
I know, as far as I see the issue is really trivial, but bothersome: most warnings refer to imports in the __init__.py files, so autodoc finds many things twice (e.g. dacbench.envs.SigmoidEnv and dacbench.envs.sigmoid.SigmoidEnv). Apparently we would need to manually set a ":noindex:" flag in one of these instances somehow... so this is pretty low on my personal priority list right now, but you're right, we should fix the warnings at some point.
