### ISSUE TITLE
Memory Leak in SGD benchmark

### ISSUE THREAD

**Issue by Steven-Adriaensen** [automl/DACBench#74]
The tensor data for the optimizee network (weights, activations) are kept in memory across steps/episodes, eventually causing out-of-memory exceptions.

**Comment by maximilianreimer** [comment]
Thanks for reporting the bug. 

Did you see the increase of the memory or even and out of memory error? If so was the increase visible over multiple episodes or just during one?

I briefly looked at the code on from what I saw it looks like the model is kept in memory for one episode since in the reset methods the model variable is been overwritten causing the old model to be freed. 

I did not find any leaf variable that was stored and still attached after one step. So there should not be an increase over the steps of one epoch either.

I'ill try to profile it. Thanks for you help.

**Comment by TheEimer** [comment]
Is this fixed @Steven-Adriaensen?
